### PR TITLE
[FEATURE] User reviews view using caching

### LINKED ISSUE #166: [FEATURE] Implement user's reviews with cache then network strategy
- [ ] Feature implementation 
- [ ] Eventual connectivity strategy

### PR DESCRIPTION
**Pull request by Laurarestrepo03**
- Closes #166 
- Adds user reviews view 
- Uses caching to store the user's reviews
- Adds ReviewCard component that disables navigation to report view when review is one's own

Others:
- Adds navigation title to review report view
- Separates reviews view and view model into its own folder

TODO:
- [x] Caching
- [x] Logic to fetch user's reviews
- [x] Change navigation button (?) → not mandatory, it already works

(This image includes hardcoded reviews)

users reviews

Feature by @mar-cas3 & @Laurarestrepo03

### CODE REVIEW

**Comment by mar-cas3** [comment]
Here's the demo showing the cache functionality:
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/b78b1b0e-3f6c-42fa-a172-b837edbcf1b7


* Since cache is fetched first, there will be a cache created for each user. That way the data shown is correct even if the person signs out and changes accounts. 
* As you can see I had some trouble with the sign-in in the first instance, I'm not quite sure what that was due to, if issues persists I will look into it but in the second instance it worked fine so for now everything regarding the issue itself is done.

**Comment by mar-cas3** [comment]
(Not sure why the video won't embed into the comment)

**Comment by Laurarestrepo03** [comment]
@mar-cas3 Worked for me!

**Review by juanyepesp — APPROVED** [review]
looks great! thank you both so very much, awesome work!

**Pull request merged**
