### PR TITLE
[FIX] Upload search terms to firebase

### LINKED ISSUE #155: [FIX] Upload search items to pipeline

### PR DESCRIPTION
**Pull request by juanyepesp**
This PR implements the functionality of saving to firebase the search terms a user sends. It adds a bunch of files, but that is because it implements new ViewModels and Repositories. You can see how this works by looking at the demo below. So as Laura says, if you have any questions or want any changes made, let me know!

TODO:
- [ ] Inside analytics repo, get this information. 

CLOSING:
- closes #155 

https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/5ce315bd-48ff-48d6-a8f2-1c60241a3687

### CODE REVIEW

**Review by mar-cas3 — APPROVED** [review]
i won't request changes bc its more of a code duplication but maybe abstracting all saveSearchItems, loadInputHistory, etc methods into it's own service down the line could help with maintainability and remove the duplicated stuff here. not really an issues and just be left as a TBR! 😝

**Review by Laurarestrepo03 — APPROVED** [review]
Wow, thank you, it's so nice when others review your PR

kamala

**Comment by juanyepesp** [comment]
> i won't request changes bc its more of a code duplication but maybe abstracting all saveSearchItems, loadInputHistory, etc methods into it's own service down the line could help with maintainability and remove the duplicated stuff here. not really an issues and just be left as a TBR! 😝 

righht!! i did think about this but was also adding a lot of files, i can change it if you want but we could also leave as is for now and change later, either one is fine for me

**Comment by mar-cas3** [comment]
> > i won't request changes bc its more of a code duplication but maybe abstracting all saveSearchItems, loadInputHistory, etc methods into it's own service down the line could help with maintainability and remove the duplicated stuff here. not really an issues and just be left as a TBR! 😝
> 
> righht!! i did think about this but was also adding a lot of files, i can change it if you want but we could also leave as is for now and change later, either one is fine for me

yess we can leave it for later! it just more of a heads up

**Comment by juanyepesp** [comment]
> Wow, thank you, it's so nice when others review your PR
> 
> 
> 
> kamala

thank you!! i know its the best feeling ever <3

**Comment by mar-cas3** [comment]
azealia-banks-the-girls-are-fighting-icjpffismxwstwsxk4

**Pull request merged**
