### PR TITLE
[FIX] Changes requested in viva voce 

### LINKED ISSUE #150: [FU] View or something that explains how ForYou works
- [ ] Tutorial like view

### LINKED ISSUE #154: [FU] Explain number aggregations for spot detail
So that the user is not so confused

### LINKED ISSUE #184: [BUG] Spots images stuck in progress view when offline

### LINKED ISSUE #187: [FIX] Review creation authentication after alerts
Flow should be:
Tap 'Done' while stars are not filled → alert → stars filled → tap 'Done' → authentication

### PR DESCRIPTION
**Pull request by juanyepesp**
This changes a lot of stuff that was mentioned on the viva voce. 
- The local authentication flow does not interrupt the verification of the review first. 
- There's tips now for for you view and spot detail, so the user has more context on what is going on. In the user view I included a button that will always show the tips. This is only meant to show them for debug purposes, if you close the app session they should be dismissed.
- Images won't stay on progress view forever

If you have any issues, encounter any bugs, or want any changes made, let me know!

CLOSING ISSUES:
- closes #150 
- closes #154 
- closes #184
- closes #187 

SCREENSHOTS:

### CODE REVIEW

**Comment by Laurarestrepo03** [comment]
This also:
- Closes #187

**Comment by Laurarestrepo03** [comment]
> This also:
> 
> * Closes [[FIX] Review creation authentication after alerts #187](https://github.com/ISIS3510-202410-Team23/SwiftApp/issues/187)

Mmh I think the closes keyword didn't work here, I'll manually add it then

**Comment by juanyepesp** [comment]
> This also:
> 
> * Closes [[FIX] Review creation authentication after alerts #187](https://github.com/ISIS3510-202410-Team23/SwiftApp/issues/187)

Thanks!! I added it on the comment as well

**Review by Laurarestrepo03 — APPROVED** [review]
Thank JDY, very cool!

**Pull request merged**
