### PR TITLE
[FIX] User image size and bookmarks user mangement

### LINKED ISSUE #101: [FIX] User image should be smaller when loading
Some ideas: spinning wheel or smaller temporal image. This is how it looks like right now:

image bug

### LINKED ISSUE #117: [FIX] Save Ids are shared among users

### PR DESCRIPTION
**Pull request by mar-cas3**
* Fixes the issue where the image in the user profile view did not have a fixed size and would take up the whole container, causing weird rendering issues as reported by @Laurarestrepo03. Closes #101  🛠️ 
* Fixes an issues where the saved bookmark id's were being shared by different users. Now they are each stored with a separate key so each person that logs in keeps their saved items.  Closes #117  🔒 
    * Fixing this issue required migrating the `BookmarksService` from a singleton pattern to be an an environment object. (If you have questions regarding this change lmk and i'll document thoroughly. 👩🏼‍💻 
* Finally, fixed the formatting on the EC alter for the LoginView so they show title and description and are more readable.
* Partially implements #115, still missing the trigger for the corresponding message.

### CODE REVIEW

**Comment by Laurarestrepo03** [comment]
@mar-cas3 Regarding #101, I'm happy to report it's working now. Thank you. I will be reviewing the rest of the code later uwu


https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/bf58e33d-2359-44a1-8855-e8cbc5f06a78

**Review by Laurarestrepo03 — APPROVED** [review]
Awesome, thank you! :p

**Review by juanyepesp — APPROVED** [review]
Look good! Could you maybe explain why you declare something an environment variable instead of state? Approving anyways since it looks okay

**Comment by mar-cas3** [comment]
> Look good! Could you maybe explain why you declare something an environment variable instead of state? Approving anyways since it looks okay

@juanyepesp 

Yess, that's the swift version of dependency injection. So the original instance of the class is created on the ContentView and set as en environment or kinda of global variable. With the `@Environment` that same instance is injected into the BookmarksView.

The reason I made that change from the Singleton pattern was so it would be instantiated on a view where the user has already logged which guarantees that the `user` var in the BookmarksService isnt `nil`.

**Pull request merged**
