### PR TITLE
[FEATURE] Bookmarks BQ

### LINKED ISSUE #93: [BQ] How many people have saved restaurants with the bookmarking feature?

### PR DESCRIPTION
**Pull request by mar-cas3**
* Implements the business question on #93 (Closes #93)
* When a user goes from 0 to 1 bookmarks the usage is set to true.
* When a user goes from 1 to 0, it is set to false. 
* All other cases don't trigger an update in the firebase to avoid unnecessary updates to the data.

Demo below: 

https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/80fc3244-41b8-40b3-bfd7-e16e67d7ca4e

### CODE REVIEW

**Comment by mar-cas3** [comment]
Tagging @Alejandro1400 since he's implementing in Flutter. Here's the demo and the issue #93 has some more details on when to update the review.

**Review by Laurarestrepo03 — CHANGES_REQUESTED** [review]
More than requesting changes I have two questions:

1. If a user doesn't exist in the collection is it created? Or does it only work with users that are already there?
2. Since one case you took into account for changing the value to false is that the user stops having bookmarks, wouldn't it be better to change the question to "How many users are _currently_ using the bookmarking feature?"

Thank you!

**Comment by mar-cas3** [comment]
> More than requesting changes I have two questions:
> 
> 1. If a user doesn't exist in the collection is it created? Or does it only work with users that are already there?
> 2. Since one case you took into account for changing the value to false is that the user stops having bookmarks, wouldn't it be better to change the question to "How many users are _currently_ using the bookmarks feature?"
> 
> Thank you!

@Laurarestrepo03 
1. Yes it's created! That's like the second part of the demo, they weren't in the collection before but it created a new document with their data on the first trigger then just updated than one. 
2. I guess we could change it, but since the actual report is generated at a certain point I guess it's implicitly that it's at time when it was generated who was using it.

**Comment by Laurarestrepo03** [comment]
> > More than requesting changes I have two questions:
> > 
> > 1. If a user doesn't exist in the collection is it created? Or does it only work with users that are already there?
> > 2. Since one case you took into account for changing the value to false is that the user stops having bookmarks, wouldn't it be better to change the question to "How many users are _currently_ using the bookmarks feature?"
> > 
> > Thank you!
> 
> @Laurarestrepo03
> 
> 1. Yes it's created! That's like the second part of the demo, they weren't in the collection before but it created a new document with their data on the first trigger then just updated than one.
> 2. I guess we could change it, but since the actual report is generated at a certain point I guess it's implicitly that it's at time when it was generated who was using it.
> 
> Lmk if that answers everything 😸

1. You're right! I'm sorry for not watching it fully, I thought it had already stopped.
2. Okie 👍

Thank you, I'll approve your PR

**Review by Laurarestrepo03 — APPROVED** [review]
Thank youu

**Pull request merged**
