### PR TITLE
[FEATURE] Local database for review drafts

### LINKED ISSUE #85: [FU] Database with the JSON or equivalent of the drafted review (doest not need to have all fields filled out)

### PR DESCRIPTION
**Pull request by Laurarestrepo03**
- Closes #85 
- Creates local db to store review drafts
- Checks if there is a draft for a spot. If so, user is presented with two options: create from draft or new one
- Allows only one draft per spot
- **No** local storage for image, will be done later

Lmk if you have any questions or want changes made

**THIS VIDEO HAS SOUND 🔊**

https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/690a9858-68d3-42aa-8955-295aad1b7d07

### CODE REVIEW

**Comment by Laurarestrepo03** [comment]
@mar-cas3 @juanyepesp I will make a new commit that will delete all drafts if user logs out, should not take more than 30 min

**Comment by Laurarestrepo03** [comment]
Commit 3f7ec66662b08f522ff5de291ee6a5db52aa392f:

Deletes drafts when user logs out

**THIS VIDEO HAS SOUND 🔊**
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/b84a6261-37cf-4ffc-aa16-29dcd0166932

@mar-cas3 @juanyepesp check this out please

**Comment by mar-cas3** [comment]
this looks amazing!! thank you so much!

image

lmk if its ready for review!

**Review by mar-cas3 — APPROVED** [review]
great job!!

**Review by juanyepesp — APPROVED** [review]
this looks awesome!! thank you very much

**Pull request merged**
