### PR TITLE
[FIX] Refactored Models

### LINKED ISSUE #36: [FIX] Refactor Models to match actual data structure

### PR DESCRIPTION
**Pull request by mar-cas3**
Refactored the `Spot` and `Review` models to match data structure in Firebase.
Additionally didi all the necessary fixes so views and view models worked as before. 

Closes #36 

Notes: 
* `ReviewViewModel` should now be deleted as the reviews as passed as a param to the Views
* Some FIXME's in the ViewModels remain the should be deleted once backend integration is complete (`import FirebaseFirestore)
* Navigation with the `See more` button should be reviewed, currently if there are not users reviews (ie. if its `nil`) an empty array is passed to the View, we can maybe add an additional check in the ReviewView which displays a text or something in this case. 

 🟢 Green-lights backend integration :)

### CODE REVIEW

**Comment by Laurarestrepo03** [comment]
@mar-cas3 Hey I just wanted to ask before we review it tomorrow, but does this take into account the changes that Nicolás made to the categories doc?

**Comment by mar-cas3** [comment]
> @mar-cas3 Hey I just wanted to ask before we review it tomorrow, but does this take into account the changes that Nicolás made to the categories doc?

@Laurarestrepo03 nope, but we haven't implemented a categories model nor the backend so that can be done from scratch based on his changes

**Review by juanyepesp — APPROVED** [review]
Looks great!

**Review by Laurarestrepo03 — APPROVED** [review]
Reviewed irl, thank you! 

olivia wilde nodding

**Pull request merged**
